CREATE TABLE users(
    id BIGSERIAL PRIMARY KEY ,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE books(
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL ,
    author VARCHAR(150) NOT NULL
);

CREATE TABLE loans(
    id BIGSERIAL PRIMARY KEY ,
    user_id BIGINT NOT NULL REFERENCES  users(id),
    book_id BIGINT NOT NULL REFERENCES  books(id),
    loan_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);