ALTER TABLE book_copies DROP COLUMN isbn;

ALTER TABLE books ADD COLUMN isbn VARCHAR(50) NOT NULL DEFAULT 'REQUER_ATUALIZAÇÃO';

ALTER TABLE users ADD COLUMN role VARCHAR(50) NOT NULL DEFAULT 'USER';
ALTER TABLE users ADD COLUMN password VARCHAR(255) NOT NULL ;

ALTER TABLE loans ADD COLUMN loan_return TIMESTAMP;
ALTER TABLE loans ADD COLUMN loan_due TIMESTAMP NOT NULL ;